const el = id => document.getElementById(id);
let maxSpeed = 0, totalSpeed = 0, speedSamples = 0, tripKm = 0, lastPos = null, smoothedSpeed = 0;
const defaultConfig = { theme:'gt', maxRingSpeed:220, smoothing:true, compass:true, stats:true, actions:true, modeName:'SPORT GT+' };
let config = loadConfig();
function loadConfig(){ try { return {...defaultConfig, ...JSON.parse(localStorage.getItem('sportGtConfig') || '{}')}; } catch { return {...defaultConfig}; } }
function saveConfig(){ localStorage.setItem('sportGtConfig', JSON.stringify(config)); }
function updateClock(){ el('clock').textContent = new Date().toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'}); }
setInterval(updateClock,1000); updateClock();
function displaySpeedValue(kmh){ return Math.max(0, Math.round(kmh)); }
function kmhFromMps(mps){ return Math.max(0, (mps || 0) * 3.6); }
function distanceKm(a,b){ const R=6371; const dLat=(b.lat-a.lat)*Math.PI/180; const dLon=(b.lon-a.lon)*Math.PI/180; const lat1=a.lat*Math.PI/180; const lat2=b.lat*Math.PI/180; const x=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2; return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x)); }
function speedToColour(speed){ if(speed < 60) return '#00ff8a'; if(speed < 110) return '#00b7ff'; if(speed < 160) return '#ffb000'; return '#ff2d2d'; }
function setSpeedArc(speed){ const dash = 603; const max = Number(config.maxRingSpeed) || 220; const pct = Math.min(speed / max, 1); const arc = el('speedArc'); const colour = speedToColour(speed); arc.style.strokeDashoffset = dash - (dash * pct * .75); arc.style.stroke = colour; arc.style.filter = `drop-shadow(0 0 14px ${colour}) drop-shadow(0 0 28px ${colour}55)`; document.documentElement.style.setProperty('--speed-colour', colour); }
function setGpsStatus(accuracy){ let label = 'GPS ACTIVE'; if(typeof accuracy === 'number'){ if(accuracy <= 12) label = 'GPS STRONG'; else if(accuracy <= 35) label = 'GPS FAIR'; else label = 'GPS WEAK'; } el('gpsStatus').textContent = label; }
function updateStats(rawSpeed){ const speed = config.smoothing ? (smoothedSpeed = smoothedSpeed * 0.72 + rawSpeed * 0.28) : rawSpeed; const shown = displaySpeedValue(speed); el('speed').textContent=shown; maxSpeed=Math.max(maxSpeed,shown); if(shown>1){ totalSpeed+=shown; speedSamples++; } el('maxSpeed').textContent=Math.round(maxSpeed); el('avgSpeed').textContent=speedSamples?Math.round(totalSpeed/speedSamples):0; el('tripDistance').textContent=tripKm.toFixed(2); setSpeedArc(shown); }
function bearingToCompass(deg){ if(deg==null || Number.isNaN(deg)) return '---'; const dirs=['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW']; return dirs[Math.round(deg/22.5)%16]; }
function applyConfig(){ document.body.dataset.theme = config.theme; el('modeLabel').textContent = config.modeName || 'SPORT GT+'; el('compassWidget').classList.toggle('hidden-widget', !config.compass); el('statsGrid').classList.toggle('hidden-widget', !config.stats); el('actionsBar').classList.toggle('hidden-widget', !config.actions); el('themeSelect').value = config.theme; el('maxSpeedSelect').value = String(config.maxRingSpeed); el('modeNameInput').value = config.modeName; el('smoothToggle').checked = !!config.smoothing; el('compassToggle').checked = !!config.compass; el('statsToggle').checked = !!config.stats; el('actionsToggle').checked = !!config.actions; setSpeedArc(Number(el('speed').textContent) || 0); }
function bindSettings(){ const panel=el('settingsPanel'), overlay=el('settingsOverlay'); const open=()=>{ panel.classList.add('open'); overlay.classList.add('open'); overlay.setAttribute('aria-hidden','false'); }; const close=()=>{ panel.classList.remove('open'); overlay.classList.remove('open'); overlay.setAttribute('aria-hidden','true'); }; el('settingsButton').addEventListener('click',open); el('closeSettings').addEventListener('click',close); overlay.addEventListener('click',close); el('themeSelect').addEventListener('change',e=>{ config.theme=e.target.value; saveConfig(); applyConfig(); }); el('maxSpeedSelect').addEventListener('change',e=>{ config.maxRingSpeed=Number(e.target.value); saveConfig(); applyConfig(); }); el('modeNameInput').addEventListener('input',e=>{ config.modeName=e.target.value || 'SPORT GT+'; saveConfig(); applyConfig(); }); el('smoothToggle').addEventListener('change',e=>{ config.smoothing=e.target.checked; saveConfig(); applyConfig(); }); el('compassToggle').addEventListener('change',e=>{ config.compass=e.target.checked; saveConfig(); applyConfig(); }); el('statsToggle').addEventListener('change',e=>{ config.stats=e.target.checked; saveConfig(); applyConfig(); }); el('actionsToggle').addEventListener('change',e=>{ config.actions=e.target.checked; saveConfig(); applyConfig(); }); el('resetTripButton').addEventListener('click',()=>{ maxSpeed=0; totalSpeed=0; speedSamples=0; tripKm=0; lastPos=null; smoothedSpeed=0; updateStats(0); }); el('resetSettingsButton').addEventListener('click',()=>{ config={...defaultConfig}; saveConfig(); applyConfig(); }); }
applyConfig(); bindSettings();
if('geolocation' in navigator){ navigator.geolocation.watchPosition(pos=>{ setGpsStatus(pos.coords.accuracy); const raw=kmhFromMps(pos.coords.speed); updateStats(raw); el('compass').textContent=bearingToCompass(pos.coords.heading); const current={lat:pos.coords.latitude, lon:pos.coords.longitude}; if(lastPos){ const d=distanceKm(lastPos,current); if(d<1) tripKm += d; } lastPos=current; },()=>{ el('gpsStatus').textContent='GPS UNAVAILABLE'; },{enableHighAccuracy:true, maximumAge:1000, timeout:10000}); } else { el('gpsStatus').textContent='GPS NOT SUPPORTED'; }
function openSpotify(){ location.href='spotify://'; setTimeout(()=>{ location.href='https://open.spotify.com'; },700); }
function openWaze(){ location.href='waze://'; setTimeout(()=>{ location.href='https://waze.com/ul'; },700); }
function openPhone(){ location.href='tel:'; }
function openMaps(){ location.href='maps://'; setTimeout(()=>{ location.href='https://maps.apple.com'; },700); }
