const speedEl=document.getElementById('speed'),bearingEl=document.getElementById('bearing'),maxEl=document.getElementById('maxSpeed'),avgEl=document.getElementById('avgSpeed'),tripEl=document.getElementById('tripDistance'),gpsStatus=document.getElementById('gpsStatus'),clockEl=document.getElementById('clock');
let maxSpeed=0,totalSpeed=0,speedSamples=0,tripMeters=0,lastPos=null;
function updateClock(){const now=new Date();clockEl.textContent=now.toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'});}setInterval(updateClock,1000);updateClock();
function kmhFromMs(ms){return Math.max(0,ms*3.6);}function toRad(v){return v*Math.PI/180;}function distanceMeters(a,b){const R=6371000,dLat=toRad(b.lat-a.lat),dLon=toRad(b.lon-a.lon),lat1=toRad(a.lat),lat2=toRad(b.lat);const x=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function bearingName(deg){if(deg==null||Number.isNaN(deg))return'---';const dirs=['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW'];return dirs[Math.round(deg/22.5)%16];}
function handlePosition(pos){gpsStatus.textContent='GPS active';const coords=pos.coords;const speed=coords.speed!=null?kmhFromMs(coords.speed):0;const rounded=Math.round(speed);speedEl.textContent=rounded;if(speed>1){totalSpeed+=speed;speedSamples++;maxSpeed=Math.max(maxSpeed,speed);maxEl.textContent=Math.round(maxSpeed);avgEl.textContent=Math.round(totalSpeed/speedSamples);}bearingEl.textContent=bearingName(coords.heading);const current={lat:coords.latitude,lon:coords.longitude};if(lastPos){const d=distanceMeters(lastPos,current);if(d<300)tripMeters+=d;}lastPos=current;tripEl.textContent=(tripMeters/1000).toFixed(2);}
function handleError(){gpsStatus.textContent='GPS unavailable';}
if('geolocation' in navigator){navigator.geolocation.watchPosition(handlePosition,handleError,{enableHighAccuracy:true,maximumAge:1000,timeout:10000});}else{gpsStatus.textContent='GPS not supported';}
function openSpotify(){window.location.href='spotify://';setTimeout(()=>{window.location.href='https://open.spotify.com';},700);}function openWaze(){window.location.href='waze://';setTimeout(()=>{window.location.href='https://waze.com/ul';},700);}function openMaps(){window.location.href='maps://';setTimeout(()=>{window.location.href='https://maps.apple.com';},700);}function openPhone(){window.location.href='tel:';}
